banco/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from clientes.views import ClientesViewSet, register_client_view, client_list_view
from enderecos.views import EnderecoViewSet, address_form_view
from contas.views import ContaViewSet
from transferencias.views import TransferenciaViewSet, transaction_view

router = routers.DefaultRouter()
router.register(r'cadastro', ClientesViewSet)
router.register(r'enderecos', EnderecoViewSet)
router.register(r'contas', ContaViewSet)
router.register(r'transferencias', TransferenciaViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('admin/', admin.site.urls),
    path('register/', register_client_view, name='register'),
    path('gerente/', client_list_view, name='gerente'),
    path('transacao/', transaction_view),
    path('address/', address_form_view)
]


"""banco URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

clientes/models.py
from django.db import models


class Cliente(models.Model):
    class Meta:
        db_table = "client"
    given_name = models.CharField('Nome', max_length=50)
    last_name = models.CharField('Sobrenome', max_length=50)
    cpf = models.CharField('CPF', max_length=14)
    email = models.EmailField('E-mail', max_length=50)
    phone = models.CharField('Telefone', max_length=50)
    birth_date = models.DateField('Data de Nascimento')

    objects = models.Manager()

    def __str__(self):
        return self.given_name + ' ' + self.last_name

clientes/forms.py
from django import forms
from .models import Cliente


class RegisterForm(forms.ModelForm):
    cpf = forms.CharField(label='CPF:',
                          widget=forms.TextInput(attrs={'placeholder': 'Digite só os números'}))

    class Meta:
        model = Cliente
        fields = {
            'given_name',
            'last_name',
            'cpf',
            'birth_date',
            'email',
            'phone'
        }

clientes/views.py
from rest_framework import viewsets
from .models import Cliente
from .serializer import ClienteSerializer, CadastroSerializer
# Templates imports abaixo
from django.shortcuts import render
from .forms import RegisterForm
from contas.models import Conta

class ClientesViewSet(viewsets.ModelViewSet):  # a ClientesViewSet é a herança da ModelViewSet
    queryset = Cliente.objects.all()
    serializer_class = CadastroSerializer

    def get_serializer_class(self):
        if self.request.method in ['GET']:
            return ClienteSerializer
        return self.serializer_class

# Funções de Templates abaixo


def register_client_view(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = RegisterForm()
    context = {'form': form}
    return render(request, 'clientes/register_client.html', context)


def client_list_view(request):
    queryset = Cliente.objects.all()  # lista de cliente
    queryset2 = Conta.objects.all()  # lista de contas
    context = {
        'object_list': queryset,
        'contas_list': queryset2
    }
    return render(request, 'gerente/lista.html', context)

templates/clientes/register_client.html
{% extends 'navbar/navbar.html' %}
{% block style %}
.wrapper{
  position: relative;
  max-width: 750px;
  width: 100%;
  background: #fff;
  padding: 34px;
  border-radius: 6px;
  box-shadow: 0 5px 10px rgba(0,0,0,0.2);
}
.wrapper h2{
  position: relative;
  font-size: 24px;
  font-weight: 600;
  color: #333;
}
.wrapper h2::before{
  content: '';
  position: absolute;
  left: 0;
  bottom: 0;
  height: 3px;
  width: 28px;
  border-radius: 12px;
  background: #cc0000;
}
.wrapper form{
  margin-top: 30px;
}
.wrapper form .input-box{
  height: 52px;
  margin: 18px 0;
}
form .input-box input{
  height: 100%;
  width: 50%;
  display: flex;
  justify-content: center;
  align-items: center;
  outline: none;
  padding: 0 15px;
  font-size: 17px;
  font-weight: 400;
  color: #333;
  border: 1.5px solid #C7BEBE;
  border-bottom-width: 2.5px;
  border-radius: 6px;
  transition: all 0.3s ease;
}
.input-box input:focus,
.input-box input:valid{
  border-color: #4070f4;
}
form .policy{
  display: flex;
  align-items: center;
}
form h3{
  color: #707070;
  font-size: 14px;
  font-weight: 500;
  margin-left: 10px;
}
.input-box.button input{
  color: #fff;
  letter-spacing: 1px;
  border: none;
  background: #cc0000;
  cursor: pointer;
}
.input-box.button input:hover{
  background: #0e4bf1;
}
form .text h3{
 color: #333;
 width: 100%;
 text-align: center;
}
form .text h3 a{
  color: #4070f4;
  text-decoration: none;
}
form .text h3 a:hover{
  text-decoration: underline;
}
{% endblock %}
{% block content %}
<div class="wrapper">
      <h2>Abra sua conta</h2>
      <form action="." method="POST">{% csrf_token %}
        <div class="input-box">
          <input type="text" name="given_name" maxlength="50" required="" id="id_given_name" placeholder="Nome ou nome composto">
        </div>
        <div class="input-box">
          <input type="text" name="last_name" maxlength="50" required="" id="id_last_name" placeholder="Sobrenome">
        </div>
        <div class="input-box">
          <input type="text" name="cpf"  required="" id="id_cpf" placeholder="CPF (só os números)">
        </div>
        <div class="input-box">
          <input type="text" name="birth_date" required="" id="id_birth_date" placeholder="Data de nascimento">
        </div>
        <div class="input-box">
          <input type="email" name="email" maxlength="50" required="" id="id_email" placeholder="email">
        </div>
        <div class="input-box">
         <input type="text" name="phone" maxlength="50" required="" id="id_phone" placeholder="telefone">
        </div>
        <div class="input-box button">
          <input type="Submit" value="Abra sua conta">
        </div>
      </form>
</div>
{% endblock %}